### ISSUE TITLE
Delta-Foxtrot squads for all factions

### ISSUE THREAD

**Issue by Scorch052** [BourbonWarfare/bwmf#100]
Currently, Only BLUFOR has Delta, Echo, and Foxtrot squads included by default and properly setup. It would be very helpful if all factions had these squads by default, considering our increasing player count.

**Comment by TheCandianVendingMachine** [comment]
In the latest commit, delta-foxtrot squads got added to every faction. Re-download BWMF and it will be solved

**Comment by AACO** [comment]
Closed as already addressed by PR #99
