### ISSUE TITLE
Weapon Squad Lead has only 1 long range radio

### ISSUE THREAD

**Issue by TheCandianVendingMachine** [BourbonWarfare/bwmf#129]
Since he is a Squad Lead he only has one radio. This is an issue since the weapons squad has long range radios for the leader, and if the WSL has a long range they can stay on FIRES to communicate.

Fix: Switch from Squad Leader to a Platoon Leader unit

**Comment by AACO** [comment]
He's literally a squad lead?

**Comment by Alex6511** [comment]
I agree with Brandon

**Comment by AACO** [comment]
But...
> He's literally a squad lead?

**Comment by Alex6511** [comment]
But... people who don't slot correctly so we end with fireteam leads with 148's and then a weapons squad lead who can't communicate with coy and his weapons teams on said 148's at the same time.

**Comment by AACO** [comment]
>people who don't slot correctly
🤔

**Comment by Alex6511** [comment]
It's been a reoccurring problem in a few sessions now where weapons squad lead has been basically left high and dry because he doesn't have 2 long ranges.

**Comment by AACO** [comment]
PEBKAC
