### ISSUE TITLE
MSV updates

### ISSUE THREAD

**Issue by Alex6511** [BourbonWarfare/bwmf#132]
- [ ] move MSV to new Holo sight as default (old sight will become alt_optics)
- [ ] add fast smoke (should we just replace red smoke with it, since red smoke is pretty useless since it bounces)
- [ ] fix Spetz team radio channel
- [ ] Spetz team should be called "Recon" when referenced in-game (groupID)

**Comment by ArgoChris** [comment]
Covered in the latest update to MSV loadouts
