### ISSUE TITLE
mission.sqm Spelling error

### ISSUE THREAD

**Issue by ForAllTheSmegs** [BourbonWarfare/bwmf#136]
Every Faction has a comment in the mission SQM. Blufors is spelt "Bluefor" which is wrong.

**Comment by Alex6511** [comment]
https://acronyms.thefreedictionary.com/BLUEFOR

(I'll fix it eventually but this isn't a real issue)

**Comment by PabstMirror** [comment]
http://lmgtfy.com/?q=how+to+spell+blue
