### ISSUE TITLE
Vanilla Arma 3 Loadouts

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#39]
Who wants to make some vanilla Arma 3 loadouts for this month in-case all the mods break with the next patch?

I think it would be nice to have anyway just in-case anything does break at anytime.

**Comment by M0zaik** [comment]
I can do that. Do we just need one set of load outs for each faction? When is the next update set to come out?

**Comment by zerithsmash** [comment]
Yeah, just csat,aaf, and nato. Maybe an FIA variant. Sometime in the next 3 weeks I think on the update. Just something to have in-case everything dies in a fire. It should be pretty easy to do for IND/BLU since you mostly just change the defines, but opfor will be more difficult since we haven't updated the gear yet.

**Comment by M0zaik** [comment]
I'm going to start with NATO and AAF, just in case anyone else wants to contribute to this as well. I'll update as I finish them. Also, how would you feel about 5.56mm and 6.5mm variants for both NATO and CSAT?

**Comment by zerithsmash** [comment]
I think he finished this, but wasn't sure how to make the PR.

**Comment by AACO** [comment]
Just send them to me, I'll make add them to the updated loadouts

**Comment by AACO** [comment]
You can also create a fork, and do pull requests.

**Comment by AACO** [comment]
I have some loadouts from Shanahan, I will try to get them added and test them sometime over the weekend. I'm a bit busy with server stuff ATM.

**Comment by AACO** [comment]
Will be resolved by PR #68. Can I get some tests on it?

**Comment by zerithsmash** [comment]
Bumping this. Can someone PLEASE help test these loadouts so we can get them merged?

**Comment by AACO** [comment]
> Bumping this. Can someone PLEASE help test these loadouts so we can get them merged?
Ha

**Comment by derbismarck** [comment]
11/10
