### ISSUE TITLE
Look into choosable loadout systems

### ISSUE THREAD

**Issue by MikeMatrix** [BourbonWarfare/bwmf#56]
- Named Subclasses for Loadout classes
- Default flag?
- Based on named subclasses that overwrite the parent settings
- Optional Feature?

**Comment by AACO** [comment]
No, super not a fan of this.
1. More shit transferred over the wire post init
2. More shit padding the framework.
3. Complicates changing loadouts (Two+ loadouts per slot?)
4. If a mission maker REALLY wants it, they can easily use a script for it.
 (This needs to be a forum post before we even get close to touching it).

**Comment by MikeMatrix** [comment]
I was more thinking along the lines of
```
  class I_Soldier_F {// rifleman
    uniform[] = {"MNP_CombatUniform_Militia_DC","MNP_CombatUniform_Militia_DB","MNP_CombatUniform_Militia_DA"};
    vest[] = {"MNP_Vest_6co_A","MNP_Vest_6co_B","MNP_Vest_UKR_B","V_TacVest_brn","V_TacVest_khk"};
    headgear[] = {"H_ShemagOpen_tan","H_Shemag_olive"};
    backpack[] = {"B_AssaultPack_rgr","B_AssaultPack_mcamo","B_AssaultPack_rgr","rhs_assault_umbts"};
    backpackItems[] = {BASE_MEDICAL};
    weapons[] = {IND_RIFLE};
    magazines[] = {IND_RIFLE_MAG,IND_BASE_GRENADES};
    items[] = {IND_BASE_TOOLS};
    linkedItems[] = {IND_BASE_LINKED};
    attachments[] = {IND_RIFLE_ATTACHMENTS};
      class Alternate_Sight {
        linkedItems[] = {IND_BASE_LINKED_ALTERNATIVE};
      };
  };
```

I might create a framework that would be easily toggleable, or a default that would easily fall back to single loadouts.

**Comment by TheCandianVendingMachine** [comment]
I think that would work well. As long as it's toggle able in CfgLoadouts.hpp, like the zoomed optics variable

**Comment by AACO** [comment]
Foooruuummmm post. How will you handle more than one alt sight?

**Comment by MikeMatrix** [comment]
just add more Subclasses.
The list of alternatives that will be shown, will be the list of childclasses for that class that applies

**Comment by AACO** [comment]
So just a formulaic approach? We need better fucking documentation.
class Alternate_Sight_n
class Alternate_Sight_n+1

**Comment by MikeMatrix** [comment]
not really, they can be randomly named. I might add an option to name the alternative loadout.
Otherwise you can probably just use the names of the classes for it.

**Comment by AACO** [comment]
Well, is that just going with the assumption that and sub class is an optic?

**Comment by MikeMatrix** [comment]
No it would be more like inheritance in that sense, it will overwrite the previous settings if that setting is available in the child class.

**Comment by AACO** [comment]
I guess I need to see more code to understand what you're thinking

**Comment by AACO** [comment]
Is this something we can close out, or do you want to keep it here for tracking?

**Comment by MikeMatrix** [comment]
Just keep it here for tracking for now. It might become something that I incorporate as an optional feature.

**Comment by AACO** [comment]
That forum post though

**Comment by AACO** [comment]
WIll be resolved by a POTATO update
