### ISSUE TITLE
Fill out BWMF wiki

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/bwmf#65]
Fill out the BWMF wiki to an initial state. You can reference Nikko's mission making guide: https://docs.google.com/document/d/1rOaSiTzfrjQde_zPIfvpv1fitDnXJjh3Jwvzm7ugdKs

**Comment by AACO** [comment]
*looks wistfully into the distance* someday, I swear

**Comment by bar56** [comment]
What more do you need?

**Comment by zerithsmash** [comment]
Did some work on this about a month ago. As always could use more eyes, suggestions, and work.
