### ISSUE TITLE
Extract some of the configs from description.ext to their own folder

### ISSUE THREAD

**Issue by AACO** [BourbonWarfare/bwmf#66]
We should probably have a configs folder in the framework with files for CfgFunctions, Params, Ace_Settings, and XEHs. This should declutter description.ext, and have each file specific to a category, for easy editing.

Things to consider:
1. Should we move the CfgLoadout file? The purist in me says, yes we should, but on a practical level mission makers edit this all the time and I don't want to add any pain to their process.
2. Should we move CfgRespawnTemplates to the f\spect\config.hpp file? All the spectator stuff bundled together?

**Comment by zerithsmash** [comment]
How does eden incorporating the description.ext into the mission.sqm affect this?

**Comment by AACO** [comment]
As far as I know/can tell it doesn't merge descripting.ext into the mission.sqm

**Comment by zerithsmash** [comment]
Now that I think about it. If you have a description.ext defined, then it will override. If you don't then it incorporates it into the mission.sqm.

**Comment by AACO** [comment]
Leaving CfgLoadout where it was
