### ISSUE TITLE
ACRE Mute Spectators

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#67]
For some reason the mute spectators button in this spectator script is hard bound to P. I got frustrated last night trying to mute the spectators to get some footage/watch in peace but listen to those in-game. My default ACRE bind (CTRL+SHIFT+DOWNARROW) was not working. I suggest we change this back to following the ACRE keybinds.

**Comment by AACO** [comment]
This was introduced when we swapped to the new spectator, I'll get a solution for this.

**Comment by MikeMatrix** [comment]
Blindly I'd say it'll be solvable with [CBA_fnc_getKeybind](https://cbateam.github.io/CBA_A3/docs/files/keybinding/fnc_getKeybind-sqf.html#CBA_fnc_getKeybind)
