### ISSUE TITLE
Spectator improvements.

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#72]
I think I just don't spend much time in spectator I guess, but lately been dying earlier so noticing these things.

1) Not an easy to way to collapse the player/unit list unless I change to a side that's not on the map. I wanted to hide the UI elements and I had to switch to a side that wasn't on the map to get rid of the list. 

2) Spectaing: Dead at the top of the screen. Probably says whoever I'm watching. This either needs to not be there or it needs to be hideable. Maybe just a hide UI button or some such.

**Comment by PabstMirror** [comment]
git gud and you won't notice these problems

**Comment by zerithsmash** [comment]
Funny since this was about 20 minutes after I found your body and took your binoculars. ;)

**Comment by AACO** [comment]
Just going to remove "Spectaing: Dead at the top of the screen." most people use free cam, or know who they're locked on to.

Re:hiding player tree, just going to unused factions is the prescribed method.

**Comment by AACO** [comment]
Hitting "u" should properly hide these elements.
