### ISSUE TITLE
Full-Duplex

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#74]
Should we consider switching to full-duplex for better radio comms? Gameplay over realism?

**Comment by AntaresTheSarcastic** [comment]
I think it's worth trying - we can gauge the reaction with everyone after a session or two and always remove it if it isn't working out fairly painlessly.  Less realistic?  Yeah, but if it serves the game environment better - I'm all for it.

**Comment by Alex6511** [comment]
Having used both in the past I prefer the current system.

**Comment by heavyhauler** [comment]
I think there are advantages and disadvantages to both. Full-duplex allows for faster and clearer comms, yet removes the realism part. Half-duplex has the realism part, but can make dealing with comms difficult. I prefer full, but the more I use half, the more I get used to it and understand what it brings to the realism.

**Comment by flyn28261** [comment]
I personally prefer the half-duplex. I think it adds to the stress excitement of a mission.

**Comment by zerithsmash** [comment]
Do we still want to test this or has Pabstmirror found a solution for our ACRE woes?

**Comment by AACO** [comment]
Going to close this, should be mostly resolved on next ACRE iteration (the rest is training/familiarization)
