### ISSUE TITLE
Mod the framework

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#75]
We obviously need to wait on some Eden kinks to be worked out, but with POTATO updates we may want to consider moving some guts of the framework to a mod format for easier updating of missions. Should take some stress off mission-makers when certain things break.

So the question is what can and cannot be incorporated into a mod? I understand the respawn system may not be able to.

**Comment by AACO** [comment]
Respawn is pretty decoupled from the reset of the framework, can be transferred to the mod. Although we need to do one of two things to ensure it works.
1. Bring (or create a new) spectate in to the mod
2. create a new function in the frame that will guarantee "closing" spectate (see current fn_ForceExit.sqf).

**Comment by AACO** [comment]
Handled by #76
