### ISSUE TITLE
Eden Integration

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#76]
What features do we want/need to integrate into Eden?

For example:

~~- Markers for units~~ Done
~~- Briefings~~ Done a while ago
~~- Can loadouts be easily integrated? I'm scared of arsenal.~~ Done
~~- In that same vein I'm not sure if radios should be due to the ease at which things could be broken~~ Done, fuck you
- What else am I missing?, Spectate, respawn?

**Comment by Waffle-SS** [comment]
we should prolly have bwmf loadouts at least load in eden
