### ISSUE TITLE
ACRE2 Version 889 quirks

### ISSUE THREAD

**Issue by zerithsmash** [BourbonWarfare/bwmf#81]
- [x] Let's disable terrain interference for now. (Will resolve the majority of 343 complaints in the short term)

If we want to go down this road we could look into tweaking radio configs for our playstyle, but it may be more trouble than it's worth.

Alternatively, consider replacing 343s with 152s until a better squad-level radio is available.

**Comment by AACO** [comment]
We downgraded, marking resolved
